<?php
return [
    'social_links'=>[
        'facebook'=>[
            'class'=>'facebook',
            'url'=>'facebook.com',
        ],
        'twitter'=>[
            'class'=>'twitter',
            'url'=>'twitter.com',
        ],
        'flickr'=>[
            'class'=>'flickr',
            'url'=>'flickr.com',
        ],
        'pinterest'=>[
            'class'=>'pinterest',
            'url'=>'pinterest.com',
        ],
        'googleplus'=>[
            'class'=>'googleplus',
            'url'=>'googleplus.com',
        ],
        'vimeo'=>[
            'class'=>'vimeo',
            'url'=>'vimeo.com',
        ],
        'youtube'=>[
            'class'=>'youtube',
            'url'=>'youtube.com',
        ],
        'mail'=>[
            'class'=>'mail',
            'url'=>'mail.com',
        ],
    ],
];